config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  root 'dashboard#index'

  resources :sale_details
  resources :products
  resources :clients
  resources :providers
  resources :services
  devise_for :users
  resources :users

  resources :sales do
    end
  get '/providers_suggestion', to: 'providers_suggestion#index'
  get '/validate_suggested_provider', to: 'validate_suggested_provider#index'
  
  get '/products_suggestion', to: 'products_suggestion#index'
  get '/validate_suggested_product', to: 'validate_suggested_product#index'

end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  PAGE_SIZE = 10
  def index
     @page = (params[:page] || 0).to_i
     @keywords = params[:keywords]

     search = Search.new(@page, PAGE_SIZE, @keywords)
     @services, @number_of_pages = search.services_by_name
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="panel-body">
      <%= form_for(@service) do |f| %>
        <% if @service.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

            <ul>
            <% service.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group row">
          <div class="col-xs-2">
            <%= f.label :name, "Nombre" %>
          </div>
          <div class="col-xs-10">
            <%= f.text_field :name, autofocus: true, placeholder: "Nombre", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-2">
            <%= f.label :description, "Descripcion" %>
          </div>
          <div class="col-xs-10">
            <%= f.text_field :description, autofocus: true, placeholder: "Descripcion", class: "form-control" %>
          </div>
        </div>

        <%= f.submit "Aceptar", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/services/_pager.html.erb
<nav>
 <ul class="pager">
  <li class="previous <%= page == 0 ? 'disabled' : '' %>">
   <%= link_to_if page > 0, "&larr; Anterior".html_safe,
                  services_path(keywords: keywords, page: page - 1) %>
  </li>
  <li class="next <%= page == @number_of_pages ? 'disabled' : '' %>">
   <%= link_to_if page < @number_of_pages, "Siguiente &rarr;".html_safe,
                  services_path(keywords: keywords, page: page + 1) %>
  </li>
 </ul>
</nav>

app/views/services/_result_search.html.erb
<table class="table">
 <thead>
  <tr>
   <%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
  </tr>
  <tr>
   <th>Nombre</th>
   <th>Descripcion</th>
   <th>Creacion</th>


   <th colspan="2"></th>
  </tr>
 </thead>

 <tbody>
  <div id="brands">
   <% @services.each do |service| %>
    <tr>
     <td><%= service.name %></td>
     <td><%= service.description %></td>
     <td><%= service.created_at %></td>

     <td>
      <%= button_to edit_service_path(service), {method: :get, class: "btn btn-info"} do %>
       <span class="glyphicon glyphicon-pencil" aria-hidden="true"> </span> Editar
      <% end %>
     </td>
     <td>
      <%= button_to service, { method: :delete, data: { confirm: '¿Está seguro?' }, class: "btn btn-danger" } do %>
       <span class="glyphicon glyphicon-trash" aria-hidden="true"> </span> Eliminar
      <% end %>
     </td>
    </tr>
   <% end %>
  </div>
 </tbody>
</table>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<div class="panel panel-default">
 <div class="panel-heading">Servicios</div>
 <div class="panel-body">
  <%= render partial: 'layouts/search_form', locals: { search_entity: 'services', word: "Servicios" } %>
  
  <br>
  <div class="col-md-5 col-md-offset-5 col-sm-5 col-sm-offset-5">
   <p>
    <%= button_to new_service_path, {method: :get, class: "btn btn-success"} do %>
     <span class="glyphicon glyphicon-plus" aria-hidden="true"> </span> Nuevo servicio
    <% end %>
   </p>
  </div>
 </div>
 <%= render partial: 'result_search' %>
</div>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>