config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  root 'dashboard#index'

  resources :sale_details
  resources :products
  resources :clients
  resources :providers
  resources :services
  devise_for :users
  resources :users

  resources :sales do
    end
  get '/providers_suggestion', to: 'providers_suggestion#index'
  get '/validate_suggested_provider', to: 'validate_suggested_provider#index'
  
  get '/products_suggestion', to: 'products_suggestion#index'
  get '/validate_suggested_product', to: 'validate_suggested_product#index'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :service


   def membership_rate_name
  self.name + ( (self.service != nil) ? ' ' + self.service.name : '' )
 end

  def service_name
	  if self.service
	   self.service.name
	  else
	   ''
	  end
 end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]
  before_action :set_combo_values, only: [:new, :edit]
  # GET /memberships
  # GET /memberships.json
  PAGE_SIZE = 10
  def index
     @page = (params[:page] || 0).to_i
     @keywords = params[:keywords]

     search = Search.new(@page, PAGE_SIZE, @keywords)
     @memberships, @number_of_pages = search.memberships_by_rate_name
  end
  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    def set_combo_values
      @services = Service.all.order(:name)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:rate_name, :sessions, :service_id, :days_expire, :price, :discount, :type, :state)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="panel-body">
      <%= form_for(@membership) do |f| %>
        <% if @membership.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

            <ul>
            <% membership.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group row">
          <div class="col-xs-2">
            <%= f.label :rate_name, "Nombre" %>
          </div>
          <div class="col-xs-10">
            <%= f.text_field :rate_name, autofocus: true, placeholder: "Nombre del precio a mostrar", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-2">
            <%= f.label :sessions, "Sesiones" %>
          </div>
          <div class="col-xs-10">
            <%= f.number_field :sessions, placeholder: "dias totales de las sesiones", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-2">
            <%= f.label :service_id, "Servicio" %>
          </div>
          <div class="col-xs-10">
            <%= f.collection_select :service_id, @services, :id, :name,
                  {selected: @membership.service_id, include_blank: 'Seleccione un servicio'}, 
                  {class: "form-control"} %>
          </div>
        </div>


       <div class="form-group row">
          <div class="col-xs-2">
            <%= f.label :days_expire, "Expira" %>
          </div>
          <div class="col-xs-10">
            <%= f.number_field :days_expire, placeholder: "Dias que expira", class: "form-control"%>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-2">
            <%= f.label :price, "Precio" %>
          </div>
          <div class="col-xs-10">
            <%= f.number_field :price, placeholder: "Precio para la", class: "form-control" , :step => 0.01%>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-2">
            <%= f.label :discount, "Descuento" %>
          </div>
          <div class="col-xs-10">
            <%= f.number_field :discount, placeholder: "descuento de la membresia", class: "form-control" , :step => 0.01%>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-2">
            <%= f.label :type, "Tipo" %>
          </div>
          <div class="col-xs-10">
            <%= f.select :type, options_for_select([["Entrada diaria","diario"],["Por registro","entrada"],["Otro","otro"]]), placeholder: "Seleccione una entrada", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-xs-2">
            <%= f.label :state, "Tipo" %>
          </div>
          <div class="col-xs-10">
            <%= f.select :state, options_for_select([["Habilitado","1"],["Deshabilitado","0"],["Otro","otro"]]), placeholder: "Seleccione un estado", class: "form-control" %>
          </div>
        </div>

        <%= f.submit "Aceptar", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/memberships/_pager.html.erb
<nav>
	<ul class="pager">
		<li class="previous <%= page == 0 ? 'disabled' : '' %>">
			<%= link_to_if page > 0, "&larr; Anterior".html_safe,
						memberships_path(keywords: keywords, page: page - 1) %>
		</li>
		<li class="next <%= page == @number_of_pages ? 'disabled' : '' %>">
			<%= link_to_if page < @number_of_pages, "Siguiente &rarr;".html_safe,
						memberships_path(keywords: keywords, page: page + 1) %>
		</li>
	</ul>
</nav>

app/views/memberships/_result_search.html.erb
<table class="table">
  <thead>
    <tr>
      <%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
    </tr>
    <tr>
      <th>Descripción</th>
      <th>Sesiones</th>
      <th>Expira</th>
      <th>Servicio</th>
      <th>Precio</th>
      <th>Descuento</th>
      <th>Tipo</th>
      <th>Estado</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <div id="brands">
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.rate_name %></td>
        <td><%= membership.sesiones %></td>
        <td><%= membership.days_expire :'dias' %></td>
        <td><%= membership.service ? membership.service.name : '' %></td>
        <td><%= number_to_currency(membership.price) %></td>
        <td><%= number_to_percentage(membership.discount, precision: 2)  %></td>
        <td><%= membership.type %></td>
        <td><%= membership.state %></td>
        <td>
          <%= button_to edit_membership_path(membership), {method: :get, class: "btn btn-info"} do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"> </span> Editar
          <% end %>
        </td>
        <td>
          <%= button_to membership, { method: :delete, data: { confirm: '¿Está seguro?' }, class: "btn btn-danger" } do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true"> </span> Eliminar
          <% end %>
        </td>
      </tr>
    <% end %>
    </div>
  </tbody>
</table>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Membresia</div>
  <div class="panel-body">
    <%= render partial: 'layouts/search_form', locals: { search_entity: 'memberships', word: "Membresias" } %>
    <br>
    <div class="col-md-5 col-md-offset-5 col-sm-5 col-sm-offset-5">
      <p>
        <%= button_to new_membership_path, {method: :get, class: "btn btn-success"} do %>
          <span class="glyphicon glyphicon-plus" aria-hidden="true"> </span> Nueva membresia
        <% end %>
      </p>
    </div>
  </div>
  <%= render partial: 'result_search' %>
</div>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rate name:</strong>
  <%= @membership.rate_name %>
</p>

<p>
  <strong>Sessions:</strong>
  <%= @membership.sessions %>
</p>

<p>
  <strong>Service:</strong>
  <%= @membership.service %>
</p>

<p>
  <strong>Days expire:</strong>
  <%= @membership.days_expire %>
</p>

<p>
  <strong>Price:</strong>
  <%= @membership.price %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @membership.discount %>
</p>

<p>
  <strong>Type:</strong>
  <%= @membership.type %>
</p>

<p>
  <strong>State:</strong>
  <%= @membership.state %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>