config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  root 'dashboard#index'

  resources :sale_details
  resources :products
  resources :clients
  resources :providers
  resources :services
  devise_for :users
  resources :users

  resources :sales do
    end
  get '/providers_suggestion', to: 'providers_suggestion#index'
  get '/validate_suggested_provider', to: 'validate_suggested_provider#index'
  
  get '/products_suggestion', to: 'products_suggestion#index'
  get '/validate_suggested_product', to: 'validate_suggested_product#index'

end

app/views/layouts/_alerts.html.erb
<div class="container-fluid">
 <div class="row">
  <% if notice.present? %>
   <div class="alert alert-info" role="alert"><%= notice %></div>
  <% end %>

  <% if alert.present? %>
   <div class="alert alert-danger" role="alert"><%= alert %></div>
  <% end %>
 </div>
</div>

app/views/layouts/_rigthbar.html.erb
<nav class="navbar navbar-default sidebar" role="navigation">
 <div class="container-fluid">
  <div class="navbar-header">
   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
   <span class="sr-only">Toggle navigation</span>
   <span class="icon-bar"></span>
   <span class="icon-bar"></span>
   <span class="icon-bar"></span>
  </button> 
 </div>
 <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
  <ul class="nav navbar-nav">

    <li class="<%= current_page?(root_path) ? "active" : "" %>">
    <a href="<%= root_path %>">
     Inicio
     <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span>
    </a>
   </li>

   <li >
    <a style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-shopping-cart">
     <%#= link_to 'Ventas', sales_path %></a>
   </li> 
 
   <li >
    <a  style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"><%= link_to 'Proveedores', providers_path %></a>  
   </li>

    <li >
    <a  style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"><%= link_to 'Productos', products_path %></a>  
   </li>

   <li >
    <a  style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"><%= link_to 'Usuarios', users_path %></a>  
   </li>

   <li >
    <a  style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"><%= link_to 'Clientes', clients_path %></a>  
   </li>

   <li >
    <a  style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"><%= link_to 'Servicios', services_path %></a>  
   </li>

  <li >
    <a  style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"><%= link_to 'Membresias', memberships_path %></a>  
   </li>


  </ul>
 </div>
 </div>
</nav>

app/views/layouts/_search_form.html.erb
<section class="search-form">
 <%= form_for search_entity, method: :get do |f| %>
  <div class="input-group">
   <%= label_tag :keywords, nil, class: "sr-only" %>
   <%= text_field_tag :keywords, nil, placeholder: "Buscar",
                       class: "form-control", value: "#{@keywords}" %>
   <span class="input-group-btn">
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
     <span class="glyphicon glyphicon-search"></span> Buscar <%= "#{word}" %>
    <% end %>
   </span>
  </div>
 <% end %>
</section>

app/views/layouts/_topbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
 <div class="container-fluid">
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="#"><%= Rails.application.class.parent_name %></a>
   </div>
   <div id="navbar" class="navbar-collapse collapse">
     <ul class="nav navbar-nav navbar-right">
       <li><a href="#">Ayuda</a></li>
       <li><a href="#">Configuración</a></li>
       <% if user_signed_in? %>
         <li> 
           <%= link_to "Salir", destroy_user_session_path, method: :delete %>
         </li>
       <% end %>
     </ul>
   <form class="navbar-form navbar-right">
     <input type="text" class="form-control" placeholder="Buscar...">
   </form>
  </div>
 </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
 <meta charset="utf-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <title>Maori</title>
 <%= csrf_meta_tags %>

 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 </head>

 <body class="<%= controller_name %> <%= action_name %>">
  <%= render 'layouts/topbar' %>

  <%# if user_signed_in? %>
   <div class="container-fluid">
    <div class="row">
     <%= render 'layouts/rigthbar' %>

     <div class="main">
      <%= render 'layouts/alerts' %>
 
      <%= yield %>
     </div>
    </div>
   </div>
  <%# else %>
   <br>
   <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">
     <%#= render 'layouts/alerts' %>
    </div>
   </div>
 
   <%#= yield %>
  <%# end %>
 </body>
</html>